import type { AuditLogItem } from './audit-log.types';

export const mockAuditLogs: AuditLogItem[] = [
  {
    id: 'log-uuid-001',
    _displayId: 'LOG-101',
    entityType: 'Settings',
    entityId: 'setting-uuid-3262',
    action: 'EXPORT',
    actorId: 'admin-uuid-001',
    actorRole: 'ADMIN',
    _actorEmail: 'admin@rideapp.mt',
    before: null,
    after: { exported: true },
    ipAddress: '192.168.1.1',
    createdAt: '2025-02-19T00:00:00Z',
  },
  {
    id: 'log-uuid-002',
    _displayId: 'LOG-102',
    entityType: 'Suppliers',
    entityId: 'sup-uuid-3262',
    action: 'CREATE',
    actorId: 'admin-uuid-001',
    actorRole: 'ADMIN',
    _actorEmail: 'admin@rideapp.mt',
    before: null,
    after: { name: 'Malta Cabs Ltd' },
    ipAddress: '192.168.1.1',
    createdAt: '2025-02-19T00:00:00Z',
  },
  {
    id: 'log-uuid-003',
    _displayId: 'LOG-103',
    entityType: 'Ride',
    entityId: 'ride-uuid-3262',
    action: 'FORCE_LOGOUT',
    actorId: 'admin-uuid-001',
    actorRole: 'ADMIN',
    _actorEmail: 'admin@rideapp.mt',
    before: { status: 'ACTIVE' },
    after: { status: 'LOGGED_OUT' },
    ipAddress: '192.168.1.1',
    createdAt: '2025-02-19T00:00:00Z',
  },
  {
    id: 'log-uuid-004',
    _displayId: 'LOG-104',
    entityType: 'User',
    entityId: 'user-uuid-3262',
    action: 'EXPORT',
    actorId: 'admin-uuid-001',
    actorRole: 'ADMIN',
    _actorEmail: 'admin@rideapp.mt',
    before: null,
    after: { exported: true },
    ipAddress: '192.168.1.1',
    createdAt: '2025-02-19T00:00:00Z',
  },
  {
    id: 'log-uuid-005',
    _displayId: 'LOG-105',
    entityType: 'Vehicle',
    entityId: 'veh-uuid-3262',
    action: 'ACTIVATE',
    actorId: 'admin-uuid-001',
    actorRole: 'ADMIN',
    _actorEmail: 'admin@rideapp.mt',
    before: { status: 'PENDING' },
    after: { status: 'ACTIVE' },
    ipAddress: '192.168.1.1',
    createdAt: '2025-02-19T00:00:00Z',
  },
  {
    id: 'log-uuid-006',
    _displayId: 'LOG-106',
    entityType: 'Settings',
    entityId: 'setting-uuid-4521',
    action: 'UPDATE',
    actorId: 'admin-uuid-002',
    actorRole: 'ADMIN',
    _actorEmail: 'ops@rideapp.mt',
    before: { theme: 'light' },
    after: { theme: 'dark' },
    ipAddress: '192.168.1.2',
    createdAt: '2025-02-18T15:30:00Z',
  },
  {
    id: 'log-uuid-007',
    _displayId: 'LOG-107',
    entityType: 'Suppliers',
    entityId: 'sup-uuid-8891',
    action: 'CREATE',
    actorId: 'admin-uuid-001',
    actorRole: 'ADMIN',
    _actorEmail: 'admin@rideapp.mt',
    before: null,
    after: { name: 'Gozo Express Ltd.' },
    ipAddress: '192.168.1.1',
    createdAt: '2025-02-18T12:00:00Z',
  },
  {
    id: 'log-uuid-008',
    _displayId: 'LOG-108',
    entityType: 'Driver',
    entityId: 'drv-uuid-2231',
    action: 'APPROVE',
    actorId: 'admin-uuid-001',
    actorRole: 'ADMIN',
    _actorEmail: 'admin@rideapp.mt',
    before: { status: 'PENDING_APPROVAL' },
    after: { status: 'ACTIVE' },
    ipAddress: '192.168.1.1',
    createdAt: '2025-02-18T10:00:00Z',
  },
  {
    id: 'log-uuid-009',
    _displayId: 'LOG-109',
    entityType: 'Ride',
    entityId: 'ride-uuid-5523',
    action: 'ISSUE_REFUND',
    actorId: 'admin-uuid-002',
    actorRole: 'ADMIN',
    _actorEmail: 'ops@rideapp.mt',
    before: { refundStatus: null },
    after: { refundStatus: 'REFUNDED', amount: 14.50 },
    ipAddress: '192.168.1.2',
    createdAt: '2025-02-17T16:00:00Z',
  },
  {
    id: 'log-uuid-010',
    _displayId: 'LOG-110',
    entityType: 'SurgeZone',
    entityId: 'zone-uuid-001',
    action: 'UPDATE',
    actorId: 'admin-uuid-001',
    actorRole: 'ADMIN',
    _actorEmail: 'admin@rideapp.mt',
    before: { multiplier: 1.5 },
    after: { multiplier: 1.8 },
    ipAddress: '192.168.1.1',
    createdAt: '2025-02-17T14:00:00Z',
  },
  {
    id: 'log-uuid-011',
    _displayId: 'LOG-111',
    entityType: 'Document',
    entityId: 'doc-uuid-7712',
    action: 'REJECT',
    actorId: 'admin-uuid-001',
    actorRole: 'ADMIN',
    _actorEmail: 'admin@rideapp.mt',
    before: { status: 'PENDING' },
    after: { status: 'REJECTED', reason: 'Expired document' },
    ipAddress: '192.168.1.1',
    createdAt: '2025-02-17T11:00:00Z',
  },
  {
    id: 'log-uuid-012',
    _displayId: 'LOG-112',
    entityType: 'User',
    entityId: 'user-uuid-9921',
    action: 'SUSPEND',
    actorId: 'admin-uuid-002',
    actorRole: 'ADMIN',
    _actorEmail: 'ops@rideapp.mt',
    before: { status: 'ACTIVE' },
    after: { status: 'SUSPENDED' },
    ipAddress: '192.168.1.2',
    createdAt: '2025-02-16T09:00:00Z',
  },
];
