import type { Dispute, DisputeKPIs, DisputeTabCounts } from './dispute.types';

export const mockDisputes: Dispute[] = [
  // --- OPEN (2) ---
  {
    id: 'ticket-uuid-001',
    _displayId: 'DSP-101',
    userId: 'user-uuid-001',
    rideId: 'ride-uuid-001',
    category: 'PAYMENT_ISSUE',
    subject: 'Overcharge',
    description:
      'I was charged €14.50 but the estimated fare was €10.00. The route taken was longer than necessary.',
    status: 'OPEN',
    _uiStatus: 'open',
    _isEscalated: false,
    assignedTo: null,
    resolvedAt: null,
    createdAt: '2025-03-25T10:15:25Z',
    updatedAt: '2025-03-25T10:15:25Z',
    _userName: 'Sarah Johnson',
    _driverName: 'Merchant Reg',
    _rideAmount: 14.5,
    _replyCount: 2,
    _replies: [
      {
        id: 'reply-1',
        authorName: 'Sarah Johnson',
        authorRole: 'USER',
        message: 'I was overcharged for my ride yesterday.',
        createdAt: '2025-03-25T10:15:25Z',
      },
      {
        id: 'reply-2',
        authorName: 'Admin',
        authorRole: 'ADMIN',
        message: "We're looking into this. Can you share more details?",
        createdAt: '2025-03-25T11:30:00Z',
      },
    ],
  },
  {
    id: 'ticket-uuid-002',
    _displayId: 'DSP-102',
    userId: 'user-uuid-002',
    rideId: 'ride-uuid-002',
    category: 'PAYMENT_ISSUE',
    subject: 'Overcharge',
    description: 'Surge pricing was applied incorrectly during non-peak hours.',
    status: 'OPEN',
    _uiStatus: 'open',
    _isEscalated: false,
    assignedTo: null,
    resolvedAt: null,
    createdAt: '2025-03-25T09:30:00Z',
    updatedAt: '2025-03-25T09:30:00Z',
    _userName: 'Sarah Johnson',
    _driverName: 'Merchant Reg',
    _rideAmount: 14.5,
    _replyCount: 2,
    _replies: [
      {
        id: 'reply-3',
        authorName: 'Sarah Johnson',
        authorRole: 'USER',
        message: 'Surge pricing applied during off-peak.',
        createdAt: '2025-03-25T09:30:00Z',
      },
      {
        id: 'reply-4',
        authorName: 'Admin',
        authorRole: 'ADMIN',
        message: 'Checking the surge logs for this period.',
        createdAt: '2025-03-25T10:00:00Z',
      },
    ],
  },

  // --- IN REVIEW (1) ---
  {
    id: 'ticket-uuid-003',
    _displayId: 'DSP-103',
    userId: 'user-uuid-003',
    rideId: 'ride-uuid-003',
    category: 'PAYMENT_ISSUE',
    subject: 'Overcharge',
    description: 'Double charged for a cancelled ride.',
    status: 'IN_PROGRESS',
    _uiStatus: 'in_review',
    _isEscalated: false,
    assignedTo: 'admin-uuid-001',
    resolvedAt: null,
    createdAt: '2025-03-25T08:45:00Z',
    updatedAt: '2025-03-25T11:00:00Z',
    _userName: 'Sarah Johnson',
    _driverName: 'Merchant Reg',
    _rideAmount: 14.5,
    _replyCount: 2,
    _replies: [
      {
        id: 'reply-5',
        authorName: 'Sarah Johnson',
        authorRole: 'USER',
        message: 'I was double charged for a ride I cancelled.',
        createdAt: '2025-03-25T08:45:00Z',
      },
      {
        id: 'reply-6',
        authorName: 'Admin',
        authorRole: 'ADMIN',
        message: 'We are reviewing the payment records.',
        createdAt: '2025-03-25T09:15:00Z',
      },
    ],
  },

  // --- RESOLVED (2) ---
  {
    id: 'ticket-uuid-004',
    _displayId: 'DSP-104',
    userId: 'user-uuid-004',
    rideId: 'ride-uuid-004',
    category: 'PAYMENT_ISSUE',
    subject: 'Overcharge',
    description: 'Refund issued for incorrect surge.',
    status: 'RESOLVED',
    _uiStatus: 'resolved',
    _isEscalated: false,
    assignedTo: 'admin-uuid-001',
    resolvedAt: '2025-03-25T14:00:00Z',
    createdAt: '2025-03-24T10:00:00Z',
    updatedAt: '2025-03-25T14:00:00Z',
    _userName: 'Sarah Johnson',
    _driverName: 'Merchant Reg',
    _rideAmount: 14.5,
    _replyCount: 2,
    _replies: [
      {
        id: 'reply-7',
        authorName: 'Sarah Johnson',
        authorRole: 'USER',
        message: 'Incorrect surge applied.',
        createdAt: '2025-03-24T10:00:00Z',
      },
      {
        id: 'reply-8',
        authorName: 'Admin',
        authorRole: 'ADMIN',
        message: 'Refund of €4.50 has been processed.',
        createdAt: '2025-03-25T14:00:00Z',
      },
    ],
  },
  {
    id: 'ticket-uuid-005',
    _displayId: 'DSP-105',
    userId: 'user-uuid-005',
    rideId: 'ride-uuid-005',
    category: 'PAYMENT_ISSUE',
    subject: 'Overcharge',
    description: 'Resolved after fare adjustment.',
    status: 'RESOLVED',
    _uiStatus: 'resolved',
    _isEscalated: false,
    assignedTo: 'admin-uuid-002',
    resolvedAt: '2025-03-25T12:00:00Z',
    createdAt: '2025-03-23T16:00:00Z',
    updatedAt: '2025-03-25T12:00:00Z',
    _userName: 'Sarah Johnson',
    _driverName: 'Merchant Reg',
    _rideAmount: 14.5,
    _replyCount: 2,
    _replies: [
      {
        id: 'reply-9',
        authorName: 'Sarah Johnson',
        authorRole: 'USER',
        message: 'Fare was higher than quoted.',
        createdAt: '2025-03-23T16:00:00Z',
      },
      {
        id: 'reply-10',
        authorName: 'Admin',
        authorRole: 'ADMIN',
        message: 'Fare adjusted. Difference credited to your wallet.',
        createdAt: '2025-03-25T12:00:00Z',
      },
    ],
  },

  // --- ESCALATED (1) ---
  {
    id: 'ticket-uuid-006',
    _displayId: 'DSP-106',
    userId: 'user-uuid-006',
    rideId: 'ride-uuid-006',
    category: 'SAFETY_CONCERN',
    subject: 'Overcharge',
    description:
      'Repeated overcharging, customer threatening legal action.',
    status: 'OPEN',
    _uiStatus: 'escalated',
    _isEscalated: true,
    assignedTo: 'admin-uuid-001',
    resolvedAt: null,
    createdAt: '2025-03-25T07:00:00Z',
    updatedAt: '2025-03-25T10:00:00Z',
    _userName: 'Sarah Johnson',
    _driverName: 'Merchant Reg',
    _rideAmount: 14.5,
    _replyCount: 2,
    _replies: [
      {
        id: 'reply-11',
        authorName: 'Sarah Johnson',
        authorRole: 'USER',
        message: 'This is the third time I have been overcharged.',
        createdAt: '2025-03-25T07:00:00Z',
      },
      {
        id: 'reply-12',
        authorName: 'Admin',
        authorRole: 'ADMIN',
        message: 'Escalating to senior support.',
        createdAt: '2025-03-25T08:00:00Z',
      },
    ],
  },
];

export const mockDisputeKPIs: DisputeKPIs = {
  total: 1284,
  open: 284,
  inReview: 18,
  escalated: 7,
  changes: { total: 12, open: 15, inReview: 15, escalated: null },
};

export const mockTabCounts: DisputeTabCounts = {
  open: 2,
  escalated: 1,
};
