import { DocumentStatus, DocumentType } from '@/types';
import type { DocumentListItem } from './document.types';

export const mockDocuments: DocumentListItem[] = [
  // --- PENDING (5) ---
  {
    id: 'doc-001',
    type: DocumentType.DRIVING_LICENSE,
    status: DocumentStatus.PENDING,
    fileUrl: '/mock/documents/driving-license-001.jpg',
    fileName: 'driving_license_front.jpg',
    fileSize: 2456000,
    mimeType: 'image/jpeg',
    expiresAt: '2027-03-15T00:00:00Z',
    rejectionReason: null,
    reviewedAt: null,
    reviewedBy: null,
    createdAt: '2025-02-20T09:30:00Z',
    updatedAt: '2025-02-20T09:30:00Z',
    entity: {
      id: 'drv-101',
      name: 'Mario Borg',
      displayId: 'D-001',
      entityType: 'driver',
    },
    _computed: {
      submittedAgo: '3 days ago',
      isAutoSuspended: false,
    },
  },
  {
    id: 'doc-002',
    type: DocumentType.INSURANCE,
    status: DocumentStatus.PENDING,
    fileUrl: '/mock/documents/insurance-002.pdf',
    fileName: 'vehicle_insurance_2025.pdf',
    fileSize: 1890000,
    mimeType: 'application/pdf',
    expiresAt: '2026-01-15T00:00:00Z',
    rejectionReason: null,
    reviewedAt: null,
    reviewedBy: null,
    createdAt: '2025-02-19T14:20:00Z',
    updatedAt: '2025-02-19T14:20:00Z',
    entity: {
      id: 'drv-102',
      name: 'Josef Camilleri',
      displayId: 'D-002',
      entityType: 'driver',
    },
    _computed: {
      submittedAgo: '4 days ago',
      isAutoSuspended: false,
    },
  },
  {
    id: 'doc-003',
    type: DocumentType.COMPANY_REGISTRATION,
    status: DocumentStatus.PENDING,
    fileUrl: '/mock/documents/company-reg-003.pdf',
    fileName: 'company_registration.pdf',
    fileSize: 3200000,
    mimeType: 'application/pdf',
    expiresAt: null,
    rejectionReason: null,
    reviewedAt: null,
    reviewedBy: null,
    createdAt: '2025-02-18T10:15:00Z',
    updatedAt: '2025-02-18T10:15:00Z',
    entity: {
      id: 'sup-201',
      name: 'Malta Ride Co.',
      displayId: 'S-001',
      entityType: 'supplier',
    },
    _computed: {
      submittedAgo: '5 days ago',
      isAutoSuspended: false,
    },
  },
  {
    id: 'doc-004',
    type: DocumentType.VEHICLE_REGISTRATION,
    status: DocumentStatus.PENDING,
    fileUrl: '/mock/documents/vehicle-reg-004.jpg',
    fileName: 'vehicle_registration.jpg',
    fileSize: 1750000,
    mimeType: 'image/jpeg',
    expiresAt: '2026-06-30T00:00:00Z',
    rejectionReason: null,
    reviewedAt: null,
    reviewedBy: null,
    createdAt: '2025-02-17T16:45:00Z',
    updatedAt: '2025-02-17T16:45:00Z',
    entity: {
      id: 'drv-103',
      name: 'Anna Spiteri',
      displayId: 'D-003',
      entityType: 'driver',
    },
    _computed: {
      submittedAgo: '6 days ago',
      isAutoSuspended: false,
    },
  },
  {
    id: 'doc-005',
    type: DocumentType.OPERATOR_LICENSE,
    status: DocumentStatus.PENDING,
    fileUrl: '/mock/documents/operator-lic-005.pdf',
    fileName: 'operator_license_2025.pdf',
    fileSize: 2100000,
    mimeType: 'application/pdf',
    expiresAt: '2026-12-31T00:00:00Z',
    rejectionReason: null,
    reviewedAt: null,
    reviewedBy: null,
    createdAt: '2025-02-16T11:00:00Z',
    updatedAt: '2025-02-16T11:00:00Z',
    entity: {
      id: 'sup-202',
      name: 'Gozo Express Ltd.',
      displayId: 'S-002',
      entityType: 'supplier',
    },
    _computed: {
      submittedAgo: '7 days ago',
      isAutoSuspended: false,
    },
  },

  // --- APPROVED (3) ---
  {
    id: 'doc-006',
    type: DocumentType.DRIVING_LICENSE,
    status: DocumentStatus.APPROVED,
    fileUrl: '/mock/documents/driving-license-006.jpg',
    fileName: 'driving_license.jpg',
    fileSize: 2300000,
    mimeType: 'image/jpeg',
    expiresAt: '2028-05-20T00:00:00Z',
    rejectionReason: null,
    reviewedAt: '2025-02-15T10:30:00Z',
    reviewedBy: 'admin-001',
    createdAt: '2025-02-10T08:00:00Z',
    updatedAt: '2025-02-15T10:30:00Z',
    entity: {
      id: 'drv-104',
      name: 'Paul Vella',
      displayId: 'D-004',
      entityType: 'driver',
    },
    _computed: {
      submittedAgo: '13 days ago',
      isAutoSuspended: false,
    },
  },
  {
    id: 'doc-007',
    type: DocumentType.VAT_CERTIFICATE,
    status: DocumentStatus.APPROVED,
    fileUrl: '/mock/documents/vat-cert-007.pdf',
    fileName: 'vat_certificate.pdf',
    fileSize: 980000,
    mimeType: 'application/pdf',
    expiresAt: '2026-12-31T00:00:00Z',
    rejectionReason: null,
    reviewedAt: '2025-02-14T15:00:00Z',
    reviewedBy: 'admin-001',
    createdAt: '2025-02-12T09:00:00Z',
    updatedAt: '2025-02-14T15:00:00Z',
    entity: {
      id: 'sup-203',
      name: 'Sliema Cabs Ltd.',
      displayId: 'S-003',
      entityType: 'supplier',
    },
    _computed: {
      submittedAgo: '11 days ago',
      isAutoSuspended: false,
    },
  },
  {
    id: 'doc-008',
    type: DocumentType.POLICE_CLEARANCE,
    status: DocumentStatus.APPROVED,
    fileUrl: '/mock/documents/police-clearance-008.pdf',
    fileName: 'police_clearance.pdf',
    fileSize: 1450000,
    mimeType: 'application/pdf',
    expiresAt: '2026-08-15T00:00:00Z',
    rejectionReason: null,
    reviewedAt: '2025-02-13T11:00:00Z',
    reviewedBy: 'admin-002',
    createdAt: '2025-02-11T14:30:00Z',
    updatedAt: '2025-02-13T11:00:00Z',
    entity: {
      id: 'drv-105',
      name: 'Carmen Grech',
      displayId: 'D-005',
      entityType: 'driver',
    },
    _computed: {
      submittedAgo: '12 days ago',
      isAutoSuspended: false,
    },
  },

  // --- REJECTED (2) ---
  {
    id: 'doc-009',
    type: DocumentType.INSURANCE,
    status: DocumentStatus.REJECTED,
    fileUrl: '/mock/documents/insurance-009.pdf',
    fileName: 'insurance_expired.pdf',
    fileSize: 1670000,
    mimeType: 'application/pdf',
    expiresAt: '2024-12-31T00:00:00Z',
    rejectionReason: 'Document expired — insurance certificate has passed its validity date',
    reviewedAt: '2025-02-12T09:45:00Z',
    reviewedBy: 'admin-001',
    createdAt: '2025-02-10T16:00:00Z',
    updatedAt: '2025-02-12T09:45:00Z',
    entity: {
      id: 'drv-106',
      name: 'Luca Fenech',
      displayId: 'D-006',
      entityType: 'driver',
    },
    _computed: {
      submittedAgo: '13 days ago',
      isAutoSuspended: false,
    },
  },
  {
    id: 'doc-010',
    type: DocumentType.VEHICLE_PHOTO_FRONT,
    status: DocumentStatus.REJECTED,
    fileUrl: '/mock/documents/vehicle-photo-010.jpg',
    fileName: 'vehicle_front_blurry.jpg',
    fileSize: 3400000,
    mimeType: 'image/jpeg',
    expiresAt: null,
    rejectionReason: 'Poor quality / unreadable — image is too blurry to verify vehicle details',
    reviewedAt: '2025-02-11T14:00:00Z',
    reviewedBy: 'admin-002',
    createdAt: '2025-02-09T12:00:00Z',
    updatedAt: '2025-02-11T14:00:00Z',
    entity: {
      id: 'drv-107',
      name: 'Robert Zammit',
      displayId: 'D-007',
      entityType: 'driver',
    },
    _computed: {
      submittedAgo: '14 days ago',
      isAutoSuspended: false,
    },
  },

  // --- EXPIRED (2) ---
  {
    id: 'doc-011',
    type: DocumentType.TAXI_LICENSE,
    status: DocumentStatus.EXPIRED,
    fileUrl: '/mock/documents/taxi-license-011.pdf',
    fileName: 'taxi_license_2024.pdf',
    fileSize: 1900000,
    mimeType: 'application/pdf',
    expiresAt: '2025-01-31T00:00:00Z',
    rejectionReason: null,
    reviewedAt: '2024-06-10T10:00:00Z',
    reviewedBy: 'admin-001',
    createdAt: '2024-06-08T09:00:00Z',
    updatedAt: '2025-02-01T00:00:00Z',
    entity: {
      id: 'drv-108',
      name: 'Daniela Pace',
      displayId: 'D-008',
      entityType: 'driver',
    },
    _computed: {
      submittedAgo: '8 months ago',
      isAutoSuspended: true,
    },
  },
  {
    id: 'doc-012',
    type: DocumentType.ROADWORTHINESS,
    status: DocumentStatus.EXPIRED,
    fileUrl: '/mock/documents/roadworthiness-012.pdf',
    fileName: 'roadworthiness_cert.pdf',
    fileSize: 1200000,
    mimeType: 'application/pdf',
    expiresAt: '2025-02-15T00:00:00Z',
    rejectionReason: null,
    reviewedAt: '2024-08-20T13:00:00Z',
    reviewedBy: 'admin-001',
    createdAt: '2024-08-18T10:00:00Z',
    updatedAt: '2025-02-15T00:00:00Z',
    entity: {
      id: 'drv-109',
      name: 'George Attard',
      displayId: 'D-009',
      entityType: 'driver',
    },
    _computed: {
      submittedAgo: '6 months ago',
      isAutoSuspended: false,
    },
  },
];

// Mock requirements for document detail view
export const mockRequirements: Record<string, { label: string; met: boolean }[]> = {
  DRIVING_LICENSE: [
    { label: 'Document is not expired', met: true },
    { label: 'Name matches profile', met: true },
    { label: 'Photo is clear and legible', met: true },
    { label: 'Correct license category (B+)', met: true },
  ],
  INSURANCE: [
    { label: 'Coverage period is valid', met: true },
    { label: 'Vehicle details match registration', met: true },
    { label: 'Third-party liability included', met: true },
    { label: 'Insurance provider is recognized', met: false },
  ],
  COMPANY_REGISTRATION: [
    { label: 'Company name matches account', met: true },
    { label: 'Registration number is valid', met: true },
    { label: 'Document is certified/stamped', met: true },
    { label: 'Directors listed match contacts', met: false },
  ],
  VEHICLE_REGISTRATION: [
    { label: 'Plate number matches vehicle', met: true },
    { label: 'Registration is current', met: true },
    { label: 'Owner name matches records', met: true },
    { label: 'Vehicle type matches category', met: true },
  ],
  OPERATOR_LICENSE: [
    { label: 'License number is valid', met: true },
    { label: 'Operator name matches company', met: true },
    { label: 'License is not expired', met: true },
    { label: 'Covers correct transport category', met: false },
  ],
  DEFAULT: [
    { label: 'Document is not expired', met: true },
    { label: 'Information is legible', met: true },
    { label: 'Matches registered details', met: true },
    { label: 'Meets format requirements', met: true },
  ],
};
