import type { NotificationCampaign, NotificationStats } from './notification.types';

export const mockCampaigns: NotificationCampaign[] = [
  {
    id: 'camp-001',
    title: 'Surge pricing active in valletta',
    body: 'Surge pricing is currently active in the Valletta area. Increased fares apply until further notice.',
    type: 'SYSTEM',
    channels: ['PUSH'],
    targetAudience: 'ALL_DRIVERS',
    targetUserIds: [],
    targetRoles: ['DRIVER'],
    status: 'SENT',
    scheduledAt: null,
    sentAt: '2025-02-13T14:30:00Z',
    sentCount: 284,
    deliveredCount: 271,
    openedCount: 198,
    failedCount: 13,
    data: null,
    createdBy: 'admin-uuid-001',
    createdAt: '2025-02-13T14:00:00Z',
    updatedAt: '2025-02-13T14:30:00Z',
  },
  {
    id: 'camp-002',
    title: 'Weekly earning summary',
    body: 'Your weekly earnings report is ready. Check your dashboard for details.',
    type: 'PAYMENT',
    channels: ['EMAIL'],
    targetAudience: 'ALL_DRIVERS',
    targetUserIds: [],
    targetRoles: ['DRIVER'],
    status: 'SENT',
    scheduledAt: null,
    sentAt: '2025-02-13T08:00:00Z',
    sentCount: 284,
    deliveredCount: 271,
    openedCount: 105,
    failedCount: 13,
    data: null,
    createdBy: 'admin-uuid-001',
    createdAt: '2025-02-13T07:00:00Z',
    updatedAt: '2025-02-13T08:00:00Z',
  },
  {
    id: 'camp-003',
    title: 'Document expiring in 7 days',
    body: 'Your driving license is expiring in 7 days. Please upload a renewed document.',
    type: 'DOCUMENT_EXPIRY',
    channels: ['PUSH', 'EMAIL'],
    targetAudience: 'SPECIFIC_USERS',
    targetUserIds: Array.from({ length: 12 }, (_, i) => `driver-uuid-${i}`),
    targetRoles: ['DRIVER'],
    status: 'SENT',
    scheduledAt: null,
    sentAt: '2025-02-13T09:15:00Z',
    sentCount: 12,
    deliveredCount: 12,
    openedCount: 9,
    failedCount: 0,
    data: null,
    createdBy: 'admin-uuid-001',
    createdAt: '2025-02-13T09:00:00Z',
    updatedAt: '2025-02-13T09:15:00Z',
  },
  {
    id: 'camp-004',
    title: 'New promo: 20% off next 3 rides',
    body: 'Use code SAVE20 to get 20% off your next 3 rides!',
    type: 'PROMOTION',
    channels: ['PUSH', 'IN_APP'],
    targetAudience: 'ALL_USERS',
    targetUserIds: [],
    targetRoles: ['USER'],
    status: 'SENT',
    scheduledAt: null,
    sentAt: '2025-02-12T18:00:00Z',
    sentCount: 1842,
    deliveredCount: 1756,
    openedCount: 892,
    failedCount: 86,
    data: { promoCode: 'SAVE20' },
    createdBy: 'admin-uuid-001',
    createdAt: '2025-02-12T17:00:00Z',
    updatedAt: '2025-02-12T18:00:00Z',
  },
  {
    id: 'camp-005',
    title: 'Service maintenance\u2014Feb 15 02:00-04:00',
    body: 'Scheduled maintenance on Feb 15. Service may be unavailable between 02:00-04:00.',
    type: 'SYSTEM',
    channels: ['EMAIL', 'IN_APP'],
    targetAudience: 'ALL',
    targetUserIds: [],
    targetRoles: [],
    status: 'SCHEDULED',
    scheduledAt: '2025-02-14T10:00:00Z',
    sentAt: null,
    sentCount: 0,
    deliveredCount: 0,
    openedCount: 0,
    failedCount: 0,
    data: null,
    createdBy: 'admin-uuid-001',
    createdAt: '2025-02-13T10:00:00Z',
    updatedAt: '2025-02-13T10:00:00Z',
  },
  {
    id: 'camp-006',
    title: 'Driver rating below threshold warning',
    body: 'Your driver rating has fallen below 4.0. Please improve your service quality.',
    type: 'SYSTEM',
    channels: ['PUSH'],
    targetAudience: 'SPECIFIC_USERS',
    targetUserIds: ['drv-1', 'drv-2', 'drv-3'],
    targetRoles: ['DRIVER'],
    status: 'SENT',
    scheduledAt: null,
    sentAt: '2025-02-12T15:30:00Z',
    sentCount: 3,
    deliveredCount: 3,
    openedCount: 2,
    failedCount: 0,
    data: null,
    createdBy: 'admin-uuid-001',
    createdAt: '2025-02-12T15:00:00Z',
    updatedAt: '2025-02-12T15:30:00Z',
  },
  {
    id: 'camp-007',
    title: 'New promo: 20% off next 3 rides',
    body: 'Extended promo for all users.',
    type: 'PROMOTION',
    channels: ['PUSH', 'IN_APP'],
    targetAudience: 'ALL_USERS',
    targetUserIds: [],
    targetRoles: ['USER'],
    status: 'SENT',
    scheduledAt: null,
    sentAt: '2025-02-12T18:00:00Z',
    sentCount: 1842,
    deliveredCount: 1756,
    openedCount: 892,
    failedCount: 86,
    data: null,
    createdBy: 'admin-uuid-001',
    createdAt: '2025-02-12T17:30:00Z',
    updatedAt: '2025-02-12T18:00:00Z',
  },
  {
    id: 'camp-008',
    title: 'Weekend surge forecast',
    body: 'Expected high demand this weekend. Position yourself in key areas.',
    type: 'SYSTEM',
    channels: ['PUSH'],
    targetAudience: 'ALL_DRIVERS',
    targetUserIds: [],
    targetRoles: ['DRIVER'],
    status: 'SCHEDULED',
    scheduledAt: '2025-02-14T16:00:00Z',
    sentAt: null,
    sentCount: 0,
    deliveredCount: 0,
    openedCount: 0,
    failedCount: 0,
    data: null,
    createdBy: 'admin-uuid-001',
    createdAt: '2025-02-13T12:00:00Z',
    updatedAt: '2025-02-13T12:00:00Z',
  },
  {
    id: 'camp-009',
    title: 'Payment processed successfully',
    body: 'Your payout has been processed and transferred to your account.',
    type: 'PAYMENT',
    channels: ['EMAIL'],
    targetAudience: 'SPECIFIC_USERS',
    targetUserIds: Array.from({ length: 12 }, (_, i) => `sup-uuid-${i}`),
    targetRoles: ['SUPPLIER'],
    status: 'SENT',
    scheduledAt: null,
    sentAt: '2025-02-12T12:25:00Z',
    sentCount: 12,
    deliveredCount: 12,
    openedCount: 8,
    failedCount: 0,
    data: null,
    createdBy: 'admin-uuid-001',
    createdAt: '2025-02-12T12:00:00Z',
    updatedAt: '2025-02-12T12:25:00Z',
  },
];

export const mockNotificationStats: NotificationStats = {
  sentToday: 1247,
  pushDeliveryRate: 94.2,
  emailOpenRate: 38.5,
  scheduledCount: 8,
};
