import type { PenaltyTransaction } from './penalty.types';

export const mockPenalties: PenaltyTransaction[] = [
  {
    id: 'penalty-uuid-001',
    _displayId: 'LOG-101',
    entityId: 'sup-uuid-001',
    entityType: 'SUPPLIER',
    type: 'NO_SHOW',
    _typeName: 'No Show',
    status: 'PENDING',
    amount: 36,
    reason: 'No show for scheduled ride',
    rideId: 'ride-uuid-001',
    voidedBy: null,
    voidedAt: null,
    createdAt: '2025-02-19T00:00:00Z',
    updatedAt: '2025-02-19T00:00:00Z',
    _entityName: 'Sara Lee',
    _entityDisplayId: 'SUP-295',
  },
  {
    id: 'penalty-uuid-002',
    _displayId: 'LOG-101',
    entityId: 'sup-uuid-002',
    entityType: 'SUPPLIER',
    type: 'POLICY_VIOLATION',
    _typeName: 'Policy Violation',
    status: 'APPLIED',
    amount: 36,
    reason: 'Violated company policy',
    rideId: null,
    voidedBy: null,
    voidedAt: null,
    createdAt: '2025-02-19T00:00:00Z',
    updatedAt: '2025-02-19T00:00:00Z',
    _entityName: 'Jane Smith',
    _entityDisplayId: 'SUP-119',
  },
  {
    id: 'penalty-uuid-003',
    _displayId: 'LOG-101',
    entityId: 'sup-uuid-003',
    entityType: 'SUPPLIER',
    type: 'LATE_CANCELLATION',
    _typeName: 'Cancellation Abuse',
    status: 'PAID',
    amount: 36,
    reason: 'Late cancellation of ride',
    rideId: 'ride-uuid-003',
    voidedBy: null,
    voidedAt: null,
    createdAt: '2025-02-19T00:00:00Z',
    updatedAt: '2025-02-19T00:00:00Z',
    _entityName: 'Ahmed Ali',
    _entityDisplayId: 'SUP-396',
  },
  {
    id: 'penalty-uuid-004',
    _displayId: 'LOG-101',
    entityId: 'drv-uuid-001',
    entityType: 'DRIVER',
    type: 'POLICY_VIOLATION',
    _typeName: 'Policy Violation',
    status: 'APPLIED',
    amount: 36,
    reason: 'Violated driving policy',
    rideId: 'ride-uuid-004',
    voidedBy: null,
    voidedAt: null,
    createdAt: '2025-02-19T00:00:00Z',
    updatedAt: '2025-02-19T00:00:00Z',
    _entityName: 'Ahmad Ali',
    _entityDisplayId: 'DRV-256',
  },
  {
    id: 'penalty-uuid-005',
    _displayId: 'LOG-101',
    entityId: 'sup-uuid-004',
    entityType: 'SUPPLIER',
    type: 'LATE_CANCELLATION',
    _typeName: 'Cancellation Abuse',
    status: 'PENDING',
    amount: 36,
    reason: 'Repeated late cancellations',
    rideId: 'ride-uuid-005',
    voidedBy: null,
    voidedAt: null,
    createdAt: '2025-02-19T00:00:00Z',
    updatedAt: '2025-02-19T00:00:00Z',
    _entityName: 'Maria Garcia',
    _entityDisplayId: 'DRV-718',
  },
  {
    id: 'penalty-uuid-006',
    _displayId: 'LOG-101',
    entityId: 'drv-uuid-002',
    entityType: 'DRIVER',
    type: 'DAMAGE',
    _typeName: 'Unsafe Driving',
    status: 'VOIDED',
    amount: 36,
    reason: 'Reported for unsafe driving',
    rideId: 'ride-uuid-006',
    voidedBy: 'admin-uuid-001',
    voidedAt: '2025-02-20T00:00:00Z',
    createdAt: '2025-02-19T00:00:00Z',
    updatedAt: '2025-02-20T00:00:00Z',
    _entityName: 'Mike Wang',
    _entityDisplayId: 'SUP-399',
  },
  {
    id: 'penalty-uuid-007',
    _displayId: 'LOG-101',
    entityId: 'sup-uuid-005',
    entityType: 'SUPPLIER',
    type: 'POLICY_VIOLATION',
    _typeName: 'Late Pickup',
    status: 'PAID',
    amount: 36,
    reason: 'Late pickup at scheduled time',
    rideId: 'ride-uuid-007',
    voidedBy: null,
    voidedAt: null,
    createdAt: '2025-02-19T00:00:00Z',
    updatedAt: '2025-02-19T00:00:00Z',
    _entityName: 'Mike Wang',
    _entityDisplayId: 'SUP-213',
  },
];
