import { SupplierStatus, SubscriptionTier, DocumentType, DocumentStatus } from '@/types';
import type { SupplierListItem, SupplierDocument } from './supplier.types';

export const mockSuppliers: SupplierListItem[] = [
  {
    id: 's-001-malta-premier',
    email: 'info@maltapremier.mt',
    companyName: 'Malta Premier Cabs',
    contactPhone: '+356 2145 6789',
    vatNumber: 'C-88721',
    emailVerified: true,
    status: SupplierStatus.ACTIVE,
    commissionRate: 12.5,
    stripeAccountId: 'acct_malta_premier_001',
    createdAt: '2025-09-15T10:00:00Z',
    updatedAt: '2026-01-20T14:30:00Z',
    subscription: { tier: SubscriptionTier.ENTERPRISE },
    _count: { drivers: 31, vehicles: 24 },
  },
  {
    id: 's-002-island-express',
    email: 'info@islandexp.mt',
    companyName: 'Island Express',
    contactPhone: '+356 2145 6789',
    vatNumber: 'C-88721',
    emailVerified: false,
    status: SupplierStatus.PENDING_VERIFICATION,
    commissionRate: 15.0,
    stripeAccountId: 'acct_island_express_002',
    createdAt: '2026-01-10T08:00:00Z',
    updatedAt: '2026-02-18T09:15:00Z',
    subscription: { tier: SubscriptionTier.STARTER },
    _count: { drivers: 31, vehicles: 24 },
  },
  {
    id: 's-003-goride-malta',
    email: 'info@goridemalta.mt',
    companyName: 'GoRide Malta',
    contactPhone: '+356 2178 3456',
    vatNumber: 'C-88721',
    emailVerified: false,
    status: SupplierStatus.PENDING_VERIFICATION,
    commissionRate: 15.0,
    stripeAccountId: null,
    createdAt: '2026-01-25T11:00:00Z',
    updatedAt: '2026-02-19T16:00:00Z',
    subscription: { tier: SubscriptionTier.STARTER },
    _count: { drivers: 31, vehicles: 24 },
  },
  {
    id: 's-004-john-camilleri',
    email: 'john@camillericabs.mt',
    companyName: 'John Camilleri',
    contactPhone: '+356 7945 1234',
    vatNumber: 'C-88721',
    emailVerified: false,
    status: SupplierStatus.PENDING_VERIFICATION,
    commissionRate: 15.0,
    stripeAccountId: null,
    createdAt: '2026-02-01T09:30:00Z',
    updatedAt: '2026-02-20T10:00:00Z',
    subscription: { tier: SubscriptionTier.STARTER },
    _count: { drivers: 31, vehicles: 24 },
  },
  {
    id: 's-005-malta-premier-2',
    email: 'fleet2@maltapremier.mt',
    companyName: 'Malta Premier Cabs',
    contactPhone: '+356 2145 9999',
    vatNumber: 'C-88721',
    emailVerified: false,
    status: SupplierStatus.PENDING_VERIFICATION,
    commissionRate: 15.0,
    stripeAccountId: null,
    createdAt: '2026-02-05T14:00:00Z',
    updatedAt: '2026-02-21T11:00:00Z',
    subscription: { tier: SubscriptionTier.STARTER },
    _count: { drivers: 31, vehicles: 24 },
  },
  {
    id: 's-006-valletta-rides',
    email: 'info@vallettarides.mt',
    companyName: 'Valletta Rides',
    contactPhone: '+356 2134 5678',
    vatNumber: 'C-88721',
    emailVerified: true,
    status: SupplierStatus.SUSPENDED,
    commissionRate: 15.0,
    stripeAccountId: 'acct_valletta_rides_006',
    createdAt: '2025-11-01T12:00:00Z',
    updatedAt: '2026-02-10T08:45:00Z',
    subscription: { tier: SubscriptionTier.STARTER },
    _count: { drivers: 31, vehicles: 24 },
  },
  {
    id: 's-007-quick-cab',
    email: 'info@quickcab.mt',
    companyName: 'Quick Cab Co',
    contactPhone: '+356 2156 7890',
    vatNumber: 'C-91234',
    emailVerified: false,
    status: SupplierStatus.REJECTED,
    commissionRate: 15.0,
    stripeAccountId: null,
    createdAt: '2026-01-05T10:00:00Z',
    updatedAt: '2026-01-15T16:30:00Z',
    subscription: { tier: SubscriptionTier.STARTER },
    _count: { drivers: 0, vehicles: 0 },
  },
];

// Mock documents keyed by supplier ID
export const mockSupplierDocuments: Record<string, SupplierDocument[]> = {
  's-002-island-express': [
    {
      id: 'doc-ie-1',
      entityId: 's-002-island-express',
      type: DocumentType.OPERATOR_LICENSE,
      status: DocumentStatus.APPROVED,
      fileUrl: '/mock/business_license.pdf',
      fileName: 'business_license.pdf',
      mimeType: 'application/pdf',
      expiresAt: '2027-09-15T00:00:00Z',
      createdAt: '2026-01-10T08:30:00Z',
    },
    {
      id: 'doc-ie-2',
      entityId: 's-002-island-express',
      type: DocumentType.INSURANCE,
      status: DocumentStatus.APPROVED,
      fileUrl: '/mock/insurance_cert.pdf',
      fileName: 'insurance_cert.pdf',
      mimeType: 'application/pdf',
      expiresAt: '2027-03-01T00:00:00Z',
      createdAt: '2026-01-10T08:35:00Z',
    },
    {
      id: 'doc-ie-3',
      entityId: 's-002-island-express',
      type: DocumentType.VAT_CERTIFICATE,
      status: DocumentStatus.PENDING,
      fileUrl: null,
      fileName: null,
      mimeType: null,
      expiresAt: null,
      createdAt: '2026-01-10T08:40:00Z',
    },
    {
      id: 'doc-ie-4',
      entityId: 's-002-island-express',
      type: DocumentType.COMPANY_REGISTRATION,
      status: DocumentStatus.APPROVED,
      fileUrl: '/mock/company_reg.pdf',
      fileName: 'company_reg.pdf',
      mimeType: 'application/pdf',
      expiresAt: null,
      createdAt: '2026-01-10T08:45:00Z',
    },
  ],
  's-003-goride-malta': [
    {
      id: 'doc-gr-1',
      entityId: 's-003-goride-malta',
      type: DocumentType.OPERATOR_LICENSE,
      status: DocumentStatus.APPROVED,
      fileUrl: '/mock/business_license.pdf',
      fileName: 'business_license.pdf',
      mimeType: 'application/pdf',
      expiresAt: '2027-06-15T00:00:00Z',
      createdAt: '2026-01-25T11:30:00Z',
    },
    {
      id: 'doc-gr-2',
      entityId: 's-003-goride-malta',
      type: DocumentType.INSURANCE,
      status: DocumentStatus.PENDING,
      fileUrl: '/mock/insurance.pdf',
      fileName: 'insurance.pdf',
      mimeType: 'application/pdf',
      expiresAt: null,
      createdAt: '2026-01-25T11:35:00Z',
    },
    {
      id: 'doc-gr-3',
      entityId: 's-003-goride-malta',
      type: DocumentType.VAT_CERTIFICATE,
      status: DocumentStatus.APPROVED,
      fileUrl: '/mock/vat_cert.pdf',
      fileName: 'vat_cert.pdf',
      mimeType: 'application/pdf',
      expiresAt: '2027-12-31T00:00:00Z',
      createdAt: '2026-01-25T11:40:00Z',
    },
    {
      id: 'doc-gr-4',
      entityId: 's-003-goride-malta',
      type: DocumentType.COMPANY_REGISTRATION,
      status: DocumentStatus.APPROVED,
      fileUrl: '/mock/company_reg.pdf',
      fileName: 'company_reg.pdf',
      mimeType: 'application/pdf',
      expiresAt: null,
      createdAt: '2026-01-25T11:45:00Z',
    },
  ],
  's-004-john-camilleri': [
    {
      id: 'doc-jc-1',
      entityId: 's-004-john-camilleri',
      type: DocumentType.OPERATOR_LICENSE,
      status: DocumentStatus.APPROVED,
      fileUrl: '/mock/business_license.pdf',
      fileName: 'business_license.pdf',
      mimeType: 'application/pdf',
      expiresAt: '2027-08-01T00:00:00Z',
      createdAt: '2026-02-01T09:45:00Z',
    },
    {
      id: 'doc-jc-2',
      entityId: 's-004-john-camilleri',
      type: DocumentType.INSURANCE,
      status: DocumentStatus.APPROVED,
      fileUrl: '/mock/insurance.pdf',
      fileName: 'insurance.pdf',
      mimeType: 'application/pdf',
      expiresAt: '2027-05-15T00:00:00Z',
      createdAt: '2026-02-01T09:50:00Z',
    },
    {
      id: 'doc-jc-3',
      entityId: 's-004-john-camilleri',
      type: DocumentType.VAT_CERTIFICATE,
      status: DocumentStatus.APPROVED,
      fileUrl: '/mock/vat.pdf',
      fileName: 'vat.pdf',
      mimeType: 'application/pdf',
      expiresAt: '2027-12-31T00:00:00Z',
      createdAt: '2026-02-01T09:55:00Z',
    },
    {
      id: 'doc-jc-4',
      entityId: 's-004-john-camilleri',
      type: DocumentType.COMPANY_REGISTRATION,
      status: DocumentStatus.APPROVED,
      fileUrl: '/mock/company_reg.pdf',
      fileName: 'company_reg.pdf',
      mimeType: 'application/pdf',
      expiresAt: null,
      createdAt: '2026-02-01T10:00:00Z',
    },
  ],
  's-005-malta-premier-2': [
    {
      id: 'doc-mp2-1',
      entityId: 's-005-malta-premier-2',
      type: DocumentType.OPERATOR_LICENSE,
      status: DocumentStatus.PENDING,
      fileUrl: '/mock/license.pdf',
      fileName: 'license.pdf',
      mimeType: 'application/pdf',
      expiresAt: null,
      createdAt: '2026-02-05T14:15:00Z',
    },
    {
      id: 'doc-mp2-2',
      entityId: 's-005-malta-premier-2',
      type: DocumentType.INSURANCE,
      status: DocumentStatus.PENDING,
      fileUrl: '/mock/insurance.pdf',
      fileName: 'insurance.pdf',
      mimeType: 'application/pdf',
      expiresAt: null,
      createdAt: '2026-02-05T14:20:00Z',
    },
    {
      id: 'doc-mp2-3',
      entityId: 's-005-malta-premier-2',
      type: DocumentType.VAT_CERTIFICATE,
      status: DocumentStatus.PENDING,
      fileUrl: null,
      fileName: null,
      mimeType: null,
      expiresAt: null,
      createdAt: '2026-02-05T14:25:00Z',
    },
    {
      id: 'doc-mp2-4',
      entityId: 's-005-malta-premier-2',
      type: DocumentType.COMPANY_REGISTRATION,
      status: DocumentStatus.PENDING,
      fileUrl: '/mock/reg.pdf',
      fileName: 'reg.pdf',
      mimeType: 'application/pdf',
      expiresAt: null,
      createdAt: '2026-02-05T14:30:00Z',
    },
  ],
};

// Mock tip summary data for supplier detail
export const mockSupplierTipSummary = {
  totalTipsReceived: 3240,
  totalTipsForwarded: 2890,
  pendingForwarding: 350,
  driverBreakdown: [
    { name: 'Marco Borg', driverId: 'drv-001', tipsOwed: 120 },
    { name: 'Paul Mizzi', driverId: 'drv-002', tipsOwed: 85 },
    { name: 'David Camilleri', driverId: 'drv-007', tipsOwed: 95 },
    { name: 'Stefan Grech', driverId: 'drv-005', tipsOwed: 50 },
  ],
};

// Mock revenue summary data for supplier detail
export const mockSupplierRevenueSummary = {
  totalRideRevenue: 45200,
  platformCommission: 5650,
  supplierEarnings: 39550,
  tipPassThrough: 3240,
  totalPaid: 38200,
  outstanding: 1350,
};

// Revenue mock (not in backend supplier list - mocked for UI)
export const mockSupplierRevenue: Record<string, number> = {
  's-001-malta-premier': 45200,
  's-002-island-express': 45200,
  's-003-goride-malta': 45200,
  's-004-john-camilleri': 45200,
  's-005-malta-premier-2': 45200,
  's-006-valletta-rides': 45200,
  's-007-quick-cab': 0,
};
